### PR TITLE
Support Bulma css framework

### PR DESCRIPTION
**Pull request by andodet**
Thanks a lot for the package,  
I recently added support for [Bulma](https://bulma.io) css frramework. Hope this can be useful.

### CODE REVIEW

**Comment by lixxu** [comment]
updated the document and use black to format the code, so `0.6.0` is out.

**Comment by andodet** [comment]
Great, thanks.  
No idea how [doc](https://flask-paginate.readthedocs.io/en/latest/) rebuild is triggered, but it still seems out of date.

**Comment by lixxu** [comment]
choose master version.

**Comment by lixxu** [comment]
I built for latest version and updated the settings to always use master version as the default.

**Pull request merged**
